[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'python -m uvicorn backend.server:app --host 0.0.0.0 --port $PORT'